"""initial schema

Revision ID: f2bb4fd760b4
Revises: 
Create Date: 2026-01-27 13:48:51.907171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bb4fd760b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('herbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost_per_gram', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blend_items',
    sa.Column('blend_id', sa.Integer(), nullable=False),
    sa.Column('herb_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['blend_id'], ['blends.id'], ),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], ),
    sa.PrimaryKeyConstraint('blend_id', 'herb_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blend_items')
    op.drop_table('herbs')
    op.drop_table('blends')
    # ### end Alembic commands ###
